# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    course_services:
        class: AppBundle\Services\CourseServices
        arguments: ["@doctrine"]
    setting_services:
        class: AppBundle\Services\SettingServices
        arguments: ["@doctrine"]